import { describe, expect, it } from 'vitest'
import type { SnapProject } from '../model/types'
import { buildBlocks } from '../parser/buildBlocks'
import { SAMPLE_INPUTS } from '../model/examples'
import { exportMarkdown } from './markdown'
import { exportHtml } from './html'
import { exportJson } from './json'
import { projectToPosterSvg, diagramToSvg, projectDiagram } from './svg'
import { buildRevisionPack } from './revisionPack'
import { nowIso } from '../utils/dates'

function fixtureProject(): SnapProject {
  return {
    id: 'snap-test',
    title: 'Photosynthesis',
    slug: 'photosynthesis',
    template: 'study-notes',
    accent: 'forest',
    source: { type: 'sample', rawText: SAMPLE_INPUTS['study-notes'].text, importedAt: nowIso() },
    blocks: buildBlocks(SAMPLE_INPUTS['study-notes'].text, 'study-notes'),
    exports: [],
    createdAt: nowIso(),
    updatedAt: nowIso(),
  }
}

describe('exportMarkdown', () => {
  it('renders title, sections, and footer', () => {
    const md = exportMarkdown(fixtureProject())
    expect(md).toContain('# Photosynthesis')
    expect(md).toContain('## Key points')
    expect(md).toContain('**Chlorophyll**')
    expect(md).toContain('Generated by SpecSnap')
  })
})

describe('exportHtml', () => {
  it('produces a standalone page with inline palette CSS', () => {
    const html = exportHtml(fixtureProject())
    expect(html).toContain('<!doctype html>')
    expect(html).toContain('--accent:#366f41')
    expect(html).toContain('Photosynthesis')
    expect(html).not.toContain('<script')
    expect(html).toContain('viewport')
  })

  it('escapes HTML in content', () => {
    const project = fixtureProject()
    project.blocks = [{ id: 'b1', type: 'summary', summary: 'Dangerous <script>alert(1)</script>' }]
    const html = exportHtml(project)
    expect(html).not.toContain('<script>alert')
    expect(html).toContain('&lt;script&gt;')
  })
})

describe('exportJson', () => {
  it('round-trips the project', () => {
    const project = fixtureProject()
    const parsed = JSON.parse(exportJson(project))
    expect(parsed.app).toBe('specsnap')
    expect(parsed.project.id).toBe(project.id)
    expect(parsed.project.blocks).toHaveLength(project.blocks.length)
  })
})

describe('SVG exports', () => {
  it('poster SVG has accessibility metadata and viewBox', () => {
    const svg = projectToPosterSvg(fixtureProject())
    expect(svg).toContain('<title')
    expect(svg).toContain('<desc')
    expect(svg).toContain('viewBox=')
    expect(svg).not.toContain('<image')
  })

  it('diagram SVG renders nodes and edges', () => {
    const project = fixtureProject()
    const diagram = projectDiagram(project)
    expect(diagram).toBeDefined()
    const svg = diagramToSvg(diagram!, project.accent)
    expect(svg).toContain('<title')
    expect((svg.match(/<rect/g) ?? []).length).toBeGreaterThan(2)
  })
})

describe('buildRevisionPack', () => {
  it('creates the documented folder structure', () => {
    const files = buildRevisionPack(fixtureProject())
    const paths = files.map((f) => f.path)
    expect(paths).toContain('photosynthesis/page.html')
    expect(paths).toContain('photosynthesis/page.md')
    expect(paths).toContain('photosynthesis/project.json')
    expect(paths).toContain('photosynthesis/assets/poster.svg')
    expect(paths.some((p) => p.endsWith('README.txt'))).toBe(true)
  })
})
