import type { SnapBlock, SnapProject } from '../model/types'

function blockToMarkdown(block: SnapBlock): string {
  switch (block.type) {
    case 'heading':
      return [
        block.eyebrow ? `*${block.eyebrow}*` : '',
        `# ${block.heading}`,
        block.subheading ?? '',
      ]
        .filter(Boolean)
        .join('\n\n')
    case 'summary':
      return `## ${block.title ?? 'Summary'}\n\n${block.summary}`
    case 'key-points':
      return `## ${block.title ?? 'Key points'}\n\n${block.points.map((p) => `- ${p}`).join('\n')}`
    case 'definitions':
      return `## ${block.title ?? 'Definitions'}\n\n${block.terms
        .map((t) => `- **${t.term}** — ${t.definition}`)
        .join('\n')}`
    case 'formulas':
      return `## ${block.title ?? 'Formulas'}\n\n${block.formulas
        .map((f) => `**${f.label}**\n\n\`\`\`\n${f.expression}\n\`\`\`\n\n${f.explanation}`)
        .join('\n\n')}`
    case 'quotes':
      return `## ${block.title ?? 'Quotes'}\n\n${block.quotes
        .map((q) => `> ${q.quote}${q.explanation ? `\n\n${q.explanation}` : ''}`)
        .join('\n\n')}`
    case 'comparison': {
      const header = `| ${block.columns.join(' | ')} |`
      const divider = `| ${block.columns.map(() => '---').join(' | ')} |`
      const rows = block.rows.map((r) => `| ${r.join(' | ')} |`).join('\n')
      return `## ${block.title ?? 'Comparison'}\n\n${header}\n${divider}\n${rows}`
    }
    case 'timeline':
      return `## ${block.title ?? 'Timeline'}\n\n${block.events
        .map((e) => `- **${e.label}** — ${e.detail}`)
        .join('\n')}`
    case 'diagram':
      return `## ${block.title ?? 'Diagram'}\n\n${block.nodes.map((n) => `- ${n.label}`).join('\n')}\n\nConnections: ${block.edges
        .map((e) => {
          const from = block.nodes.find((n) => n.id === e.source)?.label ?? e.source
          const to = block.nodes.find((n) => n.id === e.target)?.label ?? e.target
          return `${from} → ${to}`
        })
        .join(', ')}`
    case 'flashcards':
      return `## ${block.title ?? 'Flashcards'}\n\n${block.cards
        .map((c, i) => `${i + 1}. **Q:** ${c.front}\n   **A:** ${c.back}`)
        .join('\n')}`
    case 'quiz':
      return `## ${block.title ?? 'Quiz'}\n\n${block.questions
        .map(
          (q, i) =>
            `${i + 1}. ${q.prompt}\n   - Answer: ${q.answer}${q.memo ? `\n   - Memo: ${q.memo}` : ''}`,
        )
        .join('\n')}`
    case 'essay-outline':
      return [
        `## ${block.title ?? 'Essay outline'}`,
        `**Thesis:** ${block.thesis}`,
        `**Arguments:**`,
        block.arguments.map((a, i) => `${i + 1}. ${a}`).join('\n'),
        block.evidenceSlots.length
          ? `**Evidence:**\n${block.evidenceSlots.map((e) => `- ${e}`).join('\n')}`
          : '',
        `**Conclusion angle:** ${block.conclusionAngle}`,
      ]
        .filter(Boolean)
        .join('\n\n')
    case 'callout':
      return `> [!${block.tone.toUpperCase()}] ${block.title ?? 'Note'}\n> ${block.body}`
    case 'export-card':
      return ''
    default:
      return ''
  }
}

export function exportMarkdown(project: SnapProject): string {
  const body = project.blocks.map(blockToMarkdown).filter(Boolean).join('\n\n---\n\n')
  const footer = `---\n\nGenerated by SpecSnap · template: ${project.template} · ${new Date().toISOString()}`
  return `${body}\n\n${footer}\n`
}
