import type { SnapProject } from '../model/types'
import { exportHtml } from './html'
import { exportMarkdown } from './markdown'
import { exportJson } from './json'
import { projectToPosterSvg, projectDiagram } from './svg'
import { diagramToSvg } from './svg'

export type RevisionPackFile = { path: string; content: string }

/**
 * Builds the full revision pack as an in-memory file list:
 *   project-name/page.html, page.md, project.json, assets/*.svg
 * The browser downloads each file; Node scripts can write the folder.
 */
export function buildRevisionPack(project: SnapProject): RevisionPackFile[] {
  const root = project.slug
  const files: RevisionPackFile[] = [
    { path: `${root}/page.html`, content: exportHtml(project) },
    { path: `${root}/page.md`, content: exportMarkdown(project) },
    { path: `${root}/project.json`, content: exportJson(project) },
    { path: `${root}/assets/poster.svg`, content: projectToPosterSvg(project) },
  ]
  const diagram = projectDiagram(project)
  if (diagram) {
    files.push({
      path: `${root}/assets/concept-map.svg`,
      content: diagramToSvg(diagram, project.accent),
    })
  }
  files.push({
    path: `${root}/README.txt`,
    content: `Revision pack for "${project.title}"\nGenerated by SpecSnap on ${new Date().toISOString()}\n\nContents:\n${files
      .map((f) => `- ${f.path}`)
      .join('\n')}\n- ${root}/README.txt\n\nOpen page.html in any browser. page.md works in any Markdown editor.\nproject.json can be re-imported into SpecSnap from Settings.\n`,
  })
  return files
}
